import { DATA_VERSIONS, DEFAULT_DATA_VERSION, type AppState } from '@/state/db';

/** Creates state owned by exactly one Uklad runtime. */
export function createAppState(): AppState {
    return {
        appDataVersion: DEFAULT_DATA_VERSION,
        appDataVersions: DATA_VERSIONS.map((version) => ({ ...version })),
        appVersionedData: {},
        itemsList: [],
        itemsById: {},
        itemsSelectedCategory: 'all',
        itemsSelectedBuilding: 'all',
        itemsSearchTerm: '',
        itemsCategories: [],
        buildingsList: [],
        corporationsList: [],
        uiTheme: 'dark',
        uiGameDataLoadPending: false,
        uiActiveTab: 'items',
        uiConfirmationDialog: {
            isOpen: false,
            title: '',
            message: '',
            confirmLabel: 'Confirm',
            cancelLabel: 'Cancel',
            confirmButtonClass: 'btn-primary',
            onConfirm: () => {},
            onCancel: undefined,
        },
        plannerSelectedItemId: null,
        plannerSelectedCorporationLevel: null,
        plannerRecipeSelections: {},
        pinnedRecipeSelections: {},
        recipeAlternativePresets: [],
        plannerTargetAmount: 60,
        basesList: [],
        energyGroups: [],
        basesCardCollapsedSections: {},
        basesSelectedBaseId: null,
        basesSelectedDetailTab: 'base',
        productionPlanModalState: {
            isOpen: false,
            baseId: null,
            editSectionId: null,
            name: '',
            selectedItemId: '',
            targetAmount: 60,
            selectedCorporationLevel: null,
            selectedInputIds: [],
            recipeSelections: {},
            matchInputs: false,
        },
    };
}
