export const EFFECT_IDS = {
    GET_THEME: 'getTheme',
    SET_THEME: 'setTheme',
    GET_DATA_VERSION: 'getDataVersion',
    SET_DATA_VERSION: 'setDataVersion',
    LOAD_GAME_DATA: 'loadGameData',
    GET_BASES: 'getBases',
    SET_BASES: 'setBases',
    GET_ENERGY_GROUPS: 'getEnergyGroups',
    SET_ENERGY_GROUPS: 'setEnergyGroups',
    GET_PINNED_RECIPES: 'getPinnedRecipes',
    SET_PINNED_RECIPES: 'setPinnedRecipes',
    GET_RECIPE_PRESETS: 'getRecipePresets',
    SET_RECIPE_PRESETS: 'setRecipePresets',
}
