export const SUB_IDS = {
    DATA_VERSION: 'dataVersion',
    DATA_VERSIONS: 'dataVersions',
    ITEMS: 'items',
    ITEMS_MAP: 'itemsMap',
    FILTERED_ITEMS: 'filteredItems',
    SELECTED_CATEGORY: 'selectedCategory',
    SEARCH_TERM: 'searchTerm',
    CATEGORIES: 'categories',
    BUILDINGS: 'buildings',
    CORPORATIONS: 'corporations',
    THEME: 'theme',
    ACTIVE_TAB: 'activeTab',
    CORPORATIONS_STATS: 'corporationsStats',
    CORPORATIONS_WITH_STATS: 'corporationsWithStats',
    SELECTED_PLANNER_ITEM: 'selectedPlannerItem',
    SELECTED_PLANNER_CORPORATION_LEVEL: 'selectedPlannerCorporationLevel',
    PLANNER_AVAILABLE_CORPORATION_LEVELS: 'availableCorporationLevels',
}